# Generated by Django 5.2.8 on 2025-12-19 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapejob',
            name='auto_scrape',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scrapejob',
            name='last_scraped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scrapejob',
            name='scrape_interval',
            field=models.PositiveIntegerField(default=60),
        ),
    ]
