# Generated by Django 5.2.8 on 2025-12-19 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_scrapejob_auto_scrape_scrapejob_last_scraped_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapejob',
            name='source_type',
            field=models.CharField(choices=[('web', 'Web Page'), ('api', 'API')], default='web', max_length=10),
        ),
    ]
