# Generated by Django 5.2.8 on 2026-01-06 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_scrapejob_source_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapeddata',
            name='cleaned_value',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scrapeddata',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scrapejob',
            name='cleaned_content',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
