# Generated by Django 5.2.8 on 2026-01-06 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0004_scrapeddata_cleaned_value_scrapeddata_metadata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapeddata',
            name='cleaned_value_tokens',
            field=models.TextField(blank=True, null=True),
        ),
    ]
