# Generated by Django 5.2.8 on 2026-01-06 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0005_scrapeddata_cleaned_value_tokens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapeddata',
            name='cleaned_value_tokens',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
